import { defineStore } from "pinia";
import { ref, computed } from "vue";

export const useBudgetStore = defineStore("budget", () => {
  // Rates per day or totals in base USD
  const hotelRate = ref(50); // per night
  const foodRate = ref(20); // per person per day
  const activitiesTotal = ref(100); // flat total for the trip
  const fuelRate = ref(0.12); // cost per km
  const tollCost = ref(20); // flat total

  const totalKm = ref(500);
  const travelers = ref(2);
  const days = ref(7);

  // Currency selection states
  const selectedCurrency = ref("INR");
  const currencies = ref({
    INR: { symbol: "₹", rate: 83.5, label: "INR (₹)" },
    USD: { symbol: "$", rate: 1.0, label: "USD ($)" },
    EUR: { symbol: "€", rate: 0.92, label: "EUR (€)" },
    GBP: { symbol: "£", rate: 0.79, label: "GBP (£)" },
    JPY: { symbol: "¥", rate: 158.0, label: "JPY (¥)" }
  });

  const activeCurrency = computed(() => {
    return currencies.value[selectedCurrency.value] || currencies.value.INR;
  });

  // Helper conversion functions
  const convert = (usdVal) => {
    return Math.round(usdVal * activeCurrency.value.rate);
  };

  const convertAndFormat = (usdVal) => {
    const converted = convert(usdVal);
    return `${activeCurrency.value.symbol}${converted.toLocaleString()}`;
  };

  // Sync with plan generated by AI
  const syncCosts = (baseCosts, durationDays, numTravelers) => {
    travelers.value = numTravelers;
    days.value = durationDays;
    
    // Fallbacks
    const hotelBase = baseCosts?.hotel || 50;
    const foodBase = baseCosts?.food || 25;
    const activitiesBase = (baseCosts?.activities || 20) * durationDays;
    const fuelBase = baseCosts?.fuel || 80;
    const tollBase = baseCosts?.tolls || 15;

    hotelRate.value = hotelBase;
    foodRate.value = foodBase;
    activitiesTotal.value = activitiesBase;
    fuelRate.value = Math.round(fuelBase / 300 * 100) / 100 || 0.15; // approximate rate
    tollCost.value = tollBase;
  };

  // Computations in base USD
  const totalHotel = computed(() => hotelRate.value * (days.value - 1));
  const totalFood = computed(() => foodRate.value * days.value * travelers.value);
  const totalFuel = computed(() => Math.round(fuelRate.value * totalKm.value));
  
  const totalBudget = computed(() => {
    return totalHotel.value + totalFood.value + totalFuel.value + activitiesTotal.value + tollCost.value;
  });

  return {
    hotelRate,
    foodRate,
    activitiesTotal,
    fuelRate,
    tollCost,
    totalKm,
    travelers,
    days,
    selectedCurrency,
    currencies,
    activeCurrency,
    convert,
    convertAndFormat,
    syncCosts,
    totalHotel,
    totalFood,
    totalFuel,
    totalBudget
  };
});
